dist:
  name: scorecard-otel-collector
  description: Scorecard AI OpenTelemetry Collector
  output_path: ./scorecard-otel-collector
  otelcol_version: 0.97.0
  version: VERSION_STRING

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.97.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.97.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.97.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.97.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.97.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.97.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.97.0

replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension => github.com/scorecard-ai/opentelemetry-collector-contrib/extension/healthcheckv2extension 9a9cd05473817f3d152248933435f3f526b72471
