receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 10000
    timeout: 1s

exporters:
  clickhouse:

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        detailed: false
      config:
        enabled: false
    grpc:
      endpoint: "localhost:13132"
      transport: "tcp"

service:
  extensions: [healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
